// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetField } from "./AssetField";

export type Asset = { uuid: string, name: string, created_at: bigint, updated_at: bigint, fields: Array<AssetField>, };
