// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

export type AssetFieldPayload = { uuid: string | null, asset_id: string, name: string, kind: Kind, value: string, };
