// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

export type NewAssetField = { uuid: string, asset_id: string, name: string, kind: Kind, text_value: string | null, number_value: number | null, date_value: string | null, };
