// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewRelation = { uuid: string, description: string, source_asset_uuid: string, target_asset_uuid: string, };
